export const TYPES = {
    IAuthController: Symbol("IAuthController"),
    IAuthServices: Symbol("IAuthServices"),
    IAuthRepository: Symbol("IAuthRepository"),
    IStudentsController: Symbol("IStudentsController"),
    IStudentsService: Symbol("IStudentsService"),
    IStudentsRepository: Symbol("IStudentsRepository"),
    IBatchesController: Symbol("IBatchesController"),
    IBatchesService: Symbol("IBatchesService"),
    IBatchesRepository: Symbol("IBatchesRepository"),
    IAttendanceController: Symbol("IAttendanceController"),
    IAttendanceService: Symbol("IAttendanceService"),
    IAttendanceRepository: Symbol("IAttendanceRepository"),
    IFeesController: Symbol("IFeesController"),
    IFeesService: Symbol("IFeesService"),
    IFeesRepository: Symbol("IFeesRepository"),
} as const
