version: "3.9"

services:

  backend:
    build: .
    container_name: attendly-backend
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - attendly-network

  redis:
    image: redis:7
    container_name: attendly-redis
    ports:
      - "6379:6379"
    networks:
      - attendly-network

networks:
  attendly-network: